<?xml version="1.0"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>opencast-security-openid-connect</artifactId>
  <packaging>bundle</packaging>
  <name>Opencast :: security-openid-connect</name>
  <parent>
    <groupId>org.opencastproject</groupId>
    <artifactId>base</artifactId>
    <version>19-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <properties>
    <opencast.basedir>${project.basedir}/../..</opencast.basedir>
    <checkstyle.skip>false</checkstyle.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.easymock</groupId>
      <artifactId>easymock</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mitre</groupId>
      <artifactId>openid-connect-common</artifactId>
      <version>1.2.6</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>org.mitre</groupId>
      <artifactId>openid-connect-client</artifactId>
      <version>1.2.6</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.nimbusds</groupId>
      <artifactId>nimbus-jose-jwt</artifactId>
      <version>4.3</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>net.minidev</groupId>
      <artifactId>json-smart</artifactId>
      <version>1.1.1</version>
    </dependency>
    <dependency>
      <groupId>net.jcip</groupId>
      <artifactId>jcip-annotations</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>1.0.5.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-core</artifactId>
      <version>3.1.4.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-userdirectory</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-core</artifactId>
      <scope>test</scope>
    </dependency>
    <!--dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-library</artifactId>
      <scope>test</scope>
    </dependency-->
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Fragment-Host>opencast-kernel</Fragment-Host>
            <Import-Package>
              com.google.gson,
              org.mitre.oauth2.model,
              org.mitre.discovery.util,
              org.mitre.openid.connect.client,
              org.mitre.openid.connect.client.service.impl,
              org.mitre.openid.connect.config,
              org.mitre.openid.connect.model,
              org.mitre.jwt.signer.service,
              org.mitre.jwt.signer.service.impl,
              org.springframework.security.core.authority.mapping,
              !org.codehaus.*,
              !org.springframework.*,
              *
            </Import-Package>
            <Export-Package>
              org.opencastproject.security.openid.connect,
              org.springframework.security.oauth2.provider,
              com.nimbusds.jwt,
              com.nimbusds.jose,
              com.nimbusds.jose.crypto,
              com.nimbusds.jose.jca,
              com.nimbusds.jose.jwk,
              com.nimbusds.jose.util,
              net.minidev.json,
              net.minidev.json.parser,
              net.jcip.*
            </Export-Package>
            <Private-Package>
              org.springframework.security.oauth2.provider,
              com.nimbusds.jose,
              com.nimbusds.jose.jwk,
              com.nimbusds.jose.util,
              com.nimbusds.jose.jca,
              com.nimbusds.jwt,
              net.minidev.json,
              net.minidev.json.parser,
              net.jcip.*
            </Private-Package>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

    <!--Import-Package>
    com.google.common.base,
    com.google.gson,
    org.mitre.oauth2.model,
    org.mitre.openid.connect.config,
    org.mitre.discovery.util,
    !*
    </Import-Package>
    <Export-Package>
    org.springframework.security.oauth2.provider,
    com.nimbusds.jose,
    com.nimbusds.jose.jwk,
    net.minidev.json,
    </Export-Package>
    <Private-Package>
    org.mitre.openid.connect.client.*,
    org.mitre.jwt.signer.service.*,
    org.springframework.security.oauth2.provider,
    org.springframework.security.core.authority.mapping,
    com.nimbusds.jose,
    com.nimbusds.jose.jwk,
    net.minidev.json,
    </Private-Package-->