services:
  elasticsearch:
    container_name: opencast-opensearch
    image: opencast/opensearch:1
    init: true
    build:
      context: .
      dockerfile: opensearch.Containerfile
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
  keycloak:
    container_name: opencast-keycloak
    image: quay.io/keycloak/keycloak:26.3
    command: start-dev --import-realm --verbose
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: opencast
    ports:
      - 127.0.0.1:8090:8080
    volumes:
      - ${PWD}/opencast-realm.json:/opt/keycloak/data/import/opencast-realm.json:ro,Z
      - ${PWD}/opencast-users-0.json:/opt/keycloak/data/import/opencast-users-0.json:ro,Z
